name: Build and Push Docker Image

on:
  push:
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Lowercase the repository owner
        id: repo_owner
        run: echo "REPOSITORY_OWNER_LOWERCASE=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.REPOSITORY_OWNER_LOWERCASE }}
          password: ${{ secrets.CR_PAT }}

      - name: Extract tag name and convert to lowercase
        id: tag_name
        run: echo "TAG_NAME=$(echo ${GITHUB_REF#refs/tags/} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ env.REPOSITORY_OWNER_LOWERCASE }}/kube-downscaler:${{ env.TAG_NAME }}
